(defun insertion-sort (array)
  (do ((j 1 (1+ j))
       (key)
       (i))
      ((= j (length array)) array)
    (setf key (aref array j))
    (setf i (1- j))
    (while (and (>= i 0)
		(> (aref array i) key))
      (setf (aref array (1+ i))
	    (aref array i))
      (decf i))
    (setf (aref array (1+ i)) key)))

(defmacro while (test &body body)
  `(do ()
       ((not ,test))
     ,@body))
